---

- hosts: webservers
  serial: 5

  vars:
    yourhaproxyserver: 127.0.0.1

  tasks:

  - name: take out of {{inventory_hostname}} from all available load balancer pool and drop open sessions to it
    haproxy: state=disabled host={{ inventory_hostname }} socket=/var/run/haproxy.sock shutdown_sessions=true
    delegate_to: "{{yourhaproxyserver}}"

  - name: actual steps would go here
    yum: name=acme-web-stack state=latest

  - name: {{inventory_hostname}} add back to load balancer pool
    haproxy: state=enabled host={{ inventory_hostname }} socket=/var/run/haproxy.sock
    delegate_to: "{{yourhaproxyserver}}"

  - name: Change a server(s) weight, when adding back in lb pool
    haproxy: state=enabled host={{ inventory_hostname }} socket=/var/run/haproxy.sock weight=10 backend=www
    delegate_to: "{{yourhaproxyserver}}"
    register: setweight
    tags: test

  - name: Print weight
    debug: var=setweight
    tags: test
