---

- hosts: webservers
  serial: 5

  tasks:

  - name: take out of load balancer pool
    haproxy: action=disable_server host={{ inventory_hostname }} socket=/var/run/haproxy.sock
    delegate_to: 127.0.0.1

  - name: actual steps would go here
    yum: name=acme-web-stack state=latest

  - name: add back to load balancer pool
    haproxy: action=enable_server host={{ inventory_hostname }} socket=/var/run/haproxy.sock
    delegate_to: 127.0.0.1
